server:
  port: 8081


spring:
  application:
    name: rise-voice-conversion-service


rise:
  conversation:
    voice:
      azure:
        enabled: true
        speech-key: ${AZURE_SPEECH_KEY}
        speech-region: ${AZURE_SPEECH_REGION}
