server:
  port: 8081

spring:
  application:
    name: rise-text-conversion-service


rise:
  conversation:
    text:
      zhipu:
        enabled: true
        api-key: ${ZHIPU_API_KEY}
        glm4:
          enabled: true
          request-url: https://open.bigmodel.cn/api/paas/v4/chat/completions
          model: glm-4

